import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { reportApi } from '../api/reportApi';
import { patientApi } from '@/features/patients/api/patientApi';
import { diagnosisApi } from '@/features/diagnoses/api/diagnosisApi';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/common/Card';
import { Button } from '@/components/common/Button';
import { FileText, Download, Activity } from 'lucide-react';
import toast from 'react-hot-toast';
import { formatApiDate } from '@/utils/dateUtils';

export default function Reports() {
  const [selectedPatientId, setSelectedPatientId] = useState('');
  const [selectedDiagnosisId, setSelectedDiagnosisId] = useState('');

  const { data: patients = [], isLoading: isLoadingPatients, isError: isErrorPatients } = useQuery({
    queryKey: ['patients'],
    queryFn: patientApi.getPatients,
  });

  const { data: diagnoses = [], isLoading: isLoadingDiagnoses, isError: isErrorDiagnoses } = useQuery({
    queryKey: ['diagnoses'],
    queryFn: diagnosisApi.getDiagnoses,
  });

  // Filter diagnoses for the selected patient and ensure they are completed
  const patientDiagnoses = diagnoses.filter(d => d.patientId === selectedPatientId && d.status === 'COMPLETED');

  // Currently we use the actual report generated by the report service.
  // We discover it by matching the diagnosisId.
  const { data: reports = [], isError: isErrorReports } = useQuery({
    queryKey: ['reports'],
    queryFn: reportApi.getReports,
  });

  const activeReportMeta = reports.find(r => r.diagnosisId === selectedDiagnosisId);
  const activeDiagnosis = diagnoses.find(d => d.id === selectedDiagnosisId);
  const activePatient = patients.find(p => p.id === selectedPatientId);

  const { data: reportDetail, isLoading: isLoadingReportDetail } = useQuery({
    queryKey: ['reportContent', activeReportMeta?.id],
    queryFn: () => reportApi.getReport(activeReportMeta!.id),
    enabled: !!activeReportMeta?.id
  });

  if (isErrorPatients) toast.error('Unable to load patients.');
  if (selectedPatientId && isErrorDiagnoses) toast.error('Unable to load diagnoses.');
  if (isErrorReports) toast.error('Unable to load clinical reports.');

  const handleDownload = () => {
    if (!reportDetail || !activePatient) return;
    try {
      const content = reportDetail.structuredReport || reportDetail.reportContent || JSON.stringify(reportDetail, null, 2);
      const blob = new Blob([content], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Clinical_Report_${activePatient.firstName}_${activePatient.lastName}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success('Download complete');
    } catch {
      toast.error('Download failed');
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm mb-6">
        <h1 className="text-xl font-bold text-slate-800">Clinical Reports</h1>
        <p className="text-sm text-slate-500">Access and download authoritative clinical decision-support reports.</p>
      </div>

      <Card className="border-brand-200 shadow-md">
        <CardHeader className="bg-brand-50 border-b border-brand-100">
          <CardTitle className="flex items-center gap-2 text-brand-800">
            <FileText className="h-5 w-5" />
            Report Selection
          </CardTitle>
        </CardHeader>
        <CardContent className="p-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-2">
              <label className="block text-sm font-semibold text-slate-700">Select Patient</label>
              <select
                value={selectedPatientId}
                onChange={(e) => { setSelectedPatientId(e.target.value); setSelectedDiagnosisId(''); }}
                disabled={isLoadingPatients}
                className="w-full rounded-md border border-slate-300 px-4 py-2.5 text-sm focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500 bg-white"
              >
                <option value="" disabled>-- Select a patient --</option>
                {patients.map(p => (
                  <option key={p.id} value={p.id}>
                    {p.firstName} {p.lastName} (ID: {p.id.substring(0, 8)})
                  </option>
                ))}
              </select>
            </div>
            
            <div className="space-y-2">
              <label className="block text-sm font-semibold text-slate-700">Select Diagnosis</label>
              <select
                value={selectedDiagnosisId}
                onChange={(e) => setSelectedDiagnosisId(e.target.value)}
                disabled={!selectedPatientId || isLoadingDiagnoses}
                className="w-full rounded-md border border-slate-300 px-4 py-2.5 text-sm focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500 disabled:bg-slate-50 bg-white"
              >
                <option value="" disabled>
                  {selectedPatientId 
                    ? (isLoadingDiagnoses ? 'Loading diagnoses...' : '-- Select diagnosis --') 
                    : 'Select a patient first'}
                </option>
                {patientDiagnoses.map(diag => (
                  <option key={diag.id} value={diag.id}>
                    {diag.predictedClass || 'Result'} — {diag.createdAt ? formatApiDate(diag.createdAt) : 'Date unavailable'}
                  </option>
                ))}
              </select>
              {selectedPatientId && !isLoadingDiagnoses && patientDiagnoses.length === 0 && (
                <p className="text-xs text-amber-600 mt-2 font-medium">No completed reports available for this patient.</p>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {selectedDiagnosisId && activeDiagnosis && activePatient && (
        <Card className="border-slate-200 mt-8 shadow-sm">
          <CardHeader className="bg-slate-50 py-4 border-b border-slate-100 flex flex-row items-center justify-between">
            <CardTitle className="text-base font-semibold text-slate-800 flex items-center gap-2">
              <Activity className="h-4 w-4 text-brand-600" />
              Clinical Report Preview
            </CardTitle>
            <Button 
              size="sm" 
              variant="outline" 
              onClick={handleDownload} 
              disabled={isLoadingReportDetail || !reportDetail}
            >
              <Download className="h-4 w-4 mr-2 text-brand-600" />
              Download Report
            </Button>
          </CardHeader>
          <CardContent className="p-0">
            {isLoadingReportDetail ? (
              <div className="p-12 text-center text-slate-500 text-sm animate-pulse">Loading report content...</div>
            ) : !reportDetail && !activeReportMeta ? (
              <div className="p-12 text-center text-amber-600 text-sm">Report generation pending backend synchronization...</div>
            ) : (
              <div className="p-6 md:p-8 bg-white font-mono text-sm text-slate-700 whitespace-pre-wrap leading-relaxed overflow-x-auto">
                <div className="mb-6 pb-6 border-b border-slate-200 grid grid-cols-2 gap-4 text-xs font-sans">
                  <div>
                    <span className="text-slate-500 block">Patient Name</span>
                    <span className="font-semibold text-slate-800">{activePatient.firstName} {activePatient.lastName}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block">Analysis Date</span>
                    <span className="font-semibold text-slate-800">{formatApiDate(activeDiagnosis.createdAt)}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block">Diagnosis ID</span>
                    <span className="font-semibold text-slate-800">{activeDiagnosis.id}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block">Prediction Confidence</span>
                    <span className="font-semibold text-slate-800">{(activeDiagnosis.confidence * 100).toFixed(1)}%</span>
                  </div>
                </div>
                {reportDetail?.structuredReport || reportDetail?.reportContent || JSON.stringify(reportDetail, null, 2)}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
