server:
  port: 8084

spring:
  application:
    name: diagnosis-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kidneystone}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# security:
#   jwt:
#     secret: ${JWT_SECRET:CHANGE_ME_MIN_64_CHAR_SECRET_KEY_HERE_REPLACE_IN_PRODUCTION}

security:
  jwt:
    secret: ${JWT_SECRET:7c222fb2927d828af22f592134e8932480637c0d79cc5f6d6287951a37c3da33c67537494411fb31061f52d0a4c28f34175b5a6be58ab5b4976451def53a2386}

ai-engine:
  base-url: ${AI_ENGINE_URL:http://localhost:8000}
  secret: ${AI_ENGINE_SECRET:}

image-service:
  base-url: ${IMAGE_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
