package com.kidneystone.report.service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.kidneystone.report.dto.ReportRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.io.ByteArrayOutputStream;

@Slf4j
@Service
@RequiredArgsConstructor
public class PdfGeneratorService {

    private final RestTemplate restTemplate;

    @Value("${api-gateway.base-url:http://localhost:8080}")
    private String gatewayBaseUrl;

    public byte[] generatePdfReport(ReportRequest request, String authHeader) {
        Document document = new Document();
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = new Font(Font.HELVETICA, 18, Font.BOLD);
            Font headerFont = new Font(Font.HELVETICA, 14, Font.BOLD);
            Font normalFont = new Font(Font.HELVETICA, 12, Font.NORMAL);

            document.add(new Paragraph("KIDNEYSTONEAI", titleFont));
            document.add(new Paragraph("Clinical AI-Assisted Kidney Stone Analysis Report\n\n", normalFont));

            document.add(new Paragraph("Patient Information", headerFont));
            document.add(new Paragraph("Patient ID: " + safe(request.getPatientId()), normalFont));
            document.add(new Paragraph("\nAnalysis Information", headerFont));
            document.add(new Paragraph("Diagnosis ID: " + safe(request.getDiagnosisId()), normalFont));
            document.add(new Paragraph("Image ID: " + safe(request.getImageId()), normalFont));
            String dateString = request.getTimestamp() != null ? request.getTimestamp().toString() : null;
            document.add(new Paragraph("Analysis Date: " + safe(dateString), normalFont));

            document.add(new Paragraph("\nAI Diagnosis", headerFont));
            document.add(new Paragraph("Prediction: " + safe(request.getPredictedClass()), normalFont));
            String conf = request.getConfidence() != null ? String.format("%.2f%%", request.getConfidence() * 100) : "N/A";
            document.add(new Paragraph("Confidence: " + conf, normalFont));
            document.add(new Paragraph("Stone Detected: " + (Boolean.TRUE.equals(request.getStoneDetected()) ? "Yes" : "No"), normalFont));

            document.add(new Paragraph("\nSeverity", headerFont));
            document.add(new Paragraph("Level: " + safe(request.getSeverityLevel()), normalFont));
            document.add(new Paragraph("Reason: " + safe(request.getSeverityReason()), normalFont));

            document.add(new Paragraph("\nTreatment", headerFont));
            document.add(new Paragraph("Category: " + safe(request.getTreatmentCategory()), normalFont));
            document.add(new Paragraph("Recommendation: " + safe(request.getTreatmentRecommendation()), normalFont));

            document.newPage();
            document.add(new Paragraph("AI VISUAL ANALYSIS\n\n", titleFont));

            // Fetch and embed images
            embedImage(document, "Original CT", gatewayBaseUrl + "/api/v1/images/download/" + request.getImageId(), authHeader, headerFont);
            embedImage(document, "Segmentation Analysis", gatewayBaseUrl + "/api/v1/diagnoses/" + request.getDiagnosisId() + "/segmentation", authHeader, headerFont);
            embedImage(document, "Grad-CAM Classification Analysis", gatewayBaseUrl + "/api/v1/diagnoses/" + request.getDiagnosisId() + "/gradcam", authHeader, headerFont);

            document.newPage();
            document.add(new Paragraph("Model Information", headerFont));
            document.add(new Paragraph("XAI Method: " + safe(request.getXaiMethod()), normalFont));
            document.add(new Paragraph("\nClinical Decision Support Disclaimer", headerFont));
            document.add(new Paragraph("This report is generated by an AI-assisted clinical decision-support system and is not a substitute for professional medical diagnosis or clinical judgment.", normalFont));

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            log.error("Failed to generate PDF report: {}", e.getMessage(), e);
            throw new RuntimeException("PDF generation failed", e);
        }
    }

    private void embedImage(Document document, String title, String url, String authHeader, Font font) {
        try {
            document.add(new Paragraph(title, font));
            document.add(new Paragraph("\n"));

            HttpHeaders headers = new HttpHeaders();
            if (authHeader != null) {
                headers.set(HttpHeaders.AUTHORIZATION, authHeader);
            }
            HttpEntity<Void> entity = new HttpEntity<>(headers);

            ResponseEntity<byte[]> response = restTemplate.exchange(url, HttpMethod.GET, entity, byte[].class);
            byte[] imageBytes = response.getBody();

            if (imageBytes != null && imageBytes.length > 0) {
                Image img = Image.getInstance(imageBytes);
                // Scale to fit roughly half the page width to keep it readable but not overflowing
                img.scaleToFit(400, 400); 
                img.setAlignment(Image.ALIGN_LEFT);
                document.add(img);
            } else {
                document.add(new Paragraph("[Image Unavailable]"));
            }
        } catch (Exception e) {
            log.warn("Could not fetch image for PDF {}: {}", title, e.getMessage());
            try {
                document.add(new Paragraph("[Image Unavailable - Fetch Error]"));
            } catch (Exception ignored) {}
        }
        try {
            document.add(new Paragraph("\n"));
        } catch (Exception ignored) {}
    }

    private String safe(String val) {
        return val != null ? val : "Not available";
    }
}
